version: 1
formatters:
  simple:
    format: '%(asctime)s-[%(levelname)s]%(message)s'
    datefmt: '%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  main_file_handler:
    class: enhanced_rotating_file_handler.enhanced_rotating_file_handler
    level: DEBUG
    formatter: simple
    filename: "log/main.log"
    when: S
    interval: 86400
    backupCount: 1200
    maxBytes: 40240000
    encoding: utf8
  perf_logger_file_handler:
    class: enhanced_rotating_file_handler.enhanced_rotating_file_handler
    level: DEBUG
    formatter: simple
    filename: "log/perf.log"
    when: S
    interval: 86400
    backupCount: 1200
    maxBytes: 40240000
    encoding: utf8
  global_statistics_logger_file_handler:
    class: enhanced_rotating_file_handler.enhanced_rotating_file_handler
    level: DEBUG
    formatter: simple
    filename: "log/global_statistics.log"
    when: S
    interval: 86400
    backupCount: 1200
    maxBytes: 40240000
    encoding: utf8
  electricBicycleEnteringEventDetector_file_handler:
    class: enhanced_rotating_file_handler.enhanced_rotating_file_handler
    level: DEBUG
    formatter: simple
    filename: "log/electricBicycleEnteringEventDetector.log"
    when: S
    interval: 86400
    backupCount: 1200
    maxBytes: 40240000
    encoding: utf8
  doorStateChangedEventDetector_file_handler:
    class: enhanced_rotating_file_handler.enhanced_rotating_file_handler
    level: DEBUG
    formatter: simple
    filename: "log/doorStateChangedEventDetector.log"
    when: S
    interval: 86400
    backupCount: 1200
    maxBytes: 80240000
    encoding: utf8
  cameraDetectVehicleEventDetector_file_handler:
    class: enhanced_rotating_file_handler.enhanced_rotating_file_handler
    level: DEBUG
    formatter: simple
    filename: "log/cameraDetectVehicleEventDetector.log"
    when: S
    interval: 86400
    backupCount: 1200
    maxBytes: 40240000
    encoding: utf8
  eventAlarmWebServiceNotifier_file_handler:
    class: enhanced_rotating_file_handler.enhanced_rotating_file_handler
    level: DEBUG
    formatter: simple
    filename: "log/eventAlarmWebServiceNotifier.log"
    when: S
    interval: 86400
    backupCount: 1200
    maxBytes: 40240000
    encoding: utf8
  elevatorJamsEventDetector_file_handler:
    class: enhanced_rotating_file_handler.enhanced_rotating_file_handler
    level: DEBUG
    formatter: simple
    filename: "log/elevatorJamsEventDetector.log"
    when: S
    interval: 86400
    backupCount: 1200
    maxBytes: 40240000
    encoding: utf8
  doorRepeatlyOpenAndCloseEventDetector_file_handler:
    class: enhanced_rotating_file_handler.enhanced_rotating_file_handler
    level: DEBUG
    formatter: simple
    filename: "log/doorRepeatlyOpenAndCloseEventDetector.log"
    when: S
    interval: 86400
    backupCount: 1200
    maxBytes: 40240000
    encoding: utf8
  gasTankEnteringEventDetector_file_handler:
    class: enhanced_rotating_file_handler.enhanced_rotating_file_handler
    level: DEBUG
    formatter: simple
    filename: "log/gasTankEnteringEventDetector.log"
    when: S
    interval: 86400
    backupCount: 1200
    maxBytes: 40240000
    encoding: utf8
  peopleStuckEventDetector_file_handler:
    class: enhanced_rotating_file_handler.enhanced_rotating_file_handler
    level: DEBUG
    formatter: simple
    filename: "log/peopleStuckEventDetector.log"
    when: S
    interval: 86400
    backupCount: 1200
    maxBytes: 40240000
    encoding: utf8
  blockingDoorEventDetector_file_handler:
    class: enhanced_rotating_file_handler.enhanced_rotating_file_handler
    level: DEBUG
    formatter: simple
    filename: "log/blockingDoorEventDetector.log"
    when: S
    interval: 86400
    backupCount: 1200
    maxBytes: 40240000
    encoding: utf8
loggers:
  sampleLogger:
    level: DEBUG
    handlers: []
    propagate: no
  globalStatisticsLogger:
    level: DEBUG
    handlers: [global_statistics_logger_file_handler]
    propagate: no
  perfLogger:
    level: DEBUG
    handlers: [perf_logger_file_handler]
    propagate: no
  electricBicycleEnteringEventDetectorLogger:
    level: DEBUG
    handlers: [electricBicycleEnteringEventDetector_file_handler]
    propagate: no
  doorStateChangedEventDetectorLogger:
    level: DEBUG
    handlers: [doorStateChangedEventDetector_file_handler]
    propagate: no
  cameraDetectVehicleEventDetectorLogger:
    level: DEBUG
    handlers: [ cameraDetectVehicleEventDetector_file_handler ]
    propagate: no
  eventAlarmWebServiceNotifierLogger:
    level: DEBUG
    handlers: [ eventAlarmWebServiceNotifier_file_handler ]
    propagate: no
  elevatorJamsEventDetectorLogger:
    level: DEBUG
    handlers: [ elevatorJamsEventDetector_file_handler ]
    propagate: no
  doorRepeatlyOpenAndCloseEventDetectorLogger:
    level: DEBUG
    handlers: [ doorRepeatlyOpenAndCloseEventDetector_file_handler ]
    propagate: no
  gasTankEnteringEventDetectorLogger:
    level: DEBUG
    handlers: [ gasTankEnteringEventDetector_file_handler ]
    propagate: no
  peopleStuckEventDetector:
    level: DEBUG
    handlers: [ peopleStuckEventDetector_file_handler ]
    propagate: no
  blockingDoorEventDetector:
    level: DEBUG
    handlers: [ blockingDoorEventDetector_file_handler ]
    propagate: no
root:
  level: DEBUG
  handlers: [ main_file_handler ]