version: 1
formatters:
  simple:
    format: '%(asctime)s-[%(levelname)s]%(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file_handler:
    class: enhanced_rotating_file_handler.enhanced_rotating_file_handler
    level: DEBUG
    formatter: simple
    filename: "log/main.log"
    when: S
    interval: 86400
    backupCount: 1200
    maxBytes: 40240000
    encoding: utf8
loggers:
  sampleLogger:
    level: DEBUG
    handlers: []
    propagate: no
root:
  level: DEBUG
  handlers: [ file_handler ]